sudo: false
os: linux
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist

script:
  - make test

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
